# Generated by Django 3.0.6 on 2020-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='extras',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extras',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='toppings',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
