# Generated by Django 3.0.6 on 2020-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200605_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extras',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='toppings',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
