# Generated by Django 3.0.6 on 2020-06-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200605_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
    ]
